---
title: "Assignment 1"
output: html_document
---

#Preprocessing

*Trips: transform dates into timestamps (note: in Python, you will have to coerce errors for faulty dates)*




*Calculate trip duration in days (you can use loops, list comprehensions or map-lambda-functions (python) to create a column that holds the numerical value of the day. You can also use the datetime package.)*




*Filter extreme (fake?) observations for durations as well as dates - start and end (trips that last 234565 days / are in the 17th or 23rd century) The minimum duration of a trip is 1 day! Hint: use percentiles/quantiles to set boundaries for extreme values - between 1 and 97, calculate and store the boundaries before subsetting. Rhint: Use percent_rank(as.numeric(variable)) to create percentiles*




*Join the countrylist data to the trips data-frame using the countrycode as a key e. [Only for python users ] Set DateTime index as the start date of a trip*


#people 

*How many people have a least a “High School” diploma? Hint: For this calculation remove missing value-rows or fill with “False”.*

*How many “Startup Founders” have attained a “Master’s Degree”? Bonus: compared to people who don’t have a formal higher education (e.g. by using the “False” occurrences)?*

*Who is the person with a Master’s Degree that has the highest number of followers? Bonus: Explore the individual further, what else can you find out?*


#Trips

*Which country received the highest number of trips? – And which the lowest?*

*Which region received the highest number of trips in 2017? Use the start of trips as a time reference.*

*Which country in “Western Europe” did travelers spent least time? – Provide visualization*

*Do nomad Startup Founders tend to have shorter or longer trips on average?*

*visualize over-time median trip duration overall (bonus: and split by world-region) The plot will look weird ^^. PyHint: Resample by week (‘W’) and calculate the size of observations. RHint: Use the floor_date function to reset dates by week.*