---
title: "Exam"
author: "Simon"
date: "22/9/2021"
output: html_document
---


```{r}
library(tidyverse)

library(skimr)

library(magrittr)
```


# load data

```{r}
data <- read_csv("startup data.csv", 
col_types = cols(founded_at = col_date(format = "%m/%d/%Y"), 
first_funding_at = col_date(format = "%m/%d/%Y"), 
last_funding_at = col_date(format = "%m/%d/%Y")))
```

# data celaning

We take a quick look at the data
```{r}
glimpse(data)
```


We start by removing columns we dont know what is as they are not described when loading the dataset.
Also some of the columns show the same thing, 

```{r}

data %<>%
  select(!c(`Unnamed: 0`, `Unnamed: 6`, status, state_code.1, object_id, avg_participants))

glimpse(data)

```

To look how wholesome the data is we skim the data

```{r}

skim(data)

```

```{r}

data %<>%
  mutate(closed_at= replace_na(closed_at, "still going"))

```


```{r}
skim(data)
```


```{r}

#We make intervals for first milestone
data %<>%
  mutate(age_first_milestone_year_int= ifelse(age_first_milestone_year <0,"before year 0",ifelse(age_first_milestone_year <= 3 , "[0-3]", ifelse(age_first_milestone_year <= 6, "]3-6]", ifelse(age_first_milestone_year <=9, "]6-9]", ifelse(age_first_milestone_year > 9, "over 9", "")))))) %>%
  mutate(age_first_milestone_year= replace_na(age_first_milestone_year, "no milestone"))

#We make intervals for last milestone
data %<>%
  mutate(age_last_milestone_year_int= ifelse(age_last_milestone_year <0,"before year 0",ifelse(age_last_milestone_year <= 3 , "[0-3]", ifelse(age_last_milestone_year <= 6, "]3-6]", ifelse(age_last_milestone_year <=9, "]6-9]", ifelse(age_last_milestone_year > 9, "over 9", "")))))) %>%
  mutate(age_last_milestone_year= replace_na(age_last_milestone_year, "no milestone"))

skim(data)

data %<>% 
  mutate(active = labels == 1) %>%
  mutate(is_CA = is_CA ==1)

```

# EDA

```{r, fig.height=12, fig.width=12, warning=FALSE}
library(GGally)
data %>% 
  select(funding_total_usd, funding_rounds, relationships,age_first_funding_year, age_last_funding_year, milestones, active) %>%
  ggpairs(legend = 1,
          mapping = ggplot2::aes(colour=active, alpha = 0.5), 
          lower = list(continuous = wrap("smooth", alpha = 0.3, size=0.1))) +
  theme(legend.position = "bottom")

```
Ja vi kan droppe de to ringe.

```{r}

data %<>%
  filter(percent_rank(funding_total_usd) <0.99) %>% 
  filter(percent_rank(funding_rounds) <0.99) %>% 
  filter(percent_rank(relationships) <0.99) %>% 
  filter(percent_rank(age_first_funding_year) <0.99) %>% 
  filter(percent_rank(age_last_funding_year) <0.99) %>% 
  filter(percent_rank(age_first_milestone_year) <0.99) %>% 
  filter(percent_rank(age_last_milestone_year) <0.99)
```

Så laver vi nogle lækre summary stats
```{r}
data %>% 
  group_by(active) %>% 
  select(relationships, milestones, funding_rounds, funding_total_usd) %>% 
  summarise_if(is.numeric, mean, na.rm = TRUE)
```
Og så videre til PCA.

# Unsupervised ML


